### ISSUE TITLE
documentation.pdf broken

### ISSUE THREAD

**Issue by diekmann** [moepinet/moeptikz#3] opened 2015-08-27 11:03 UTC
The documentation.pdf is a broken pdf.

Opening it with Adobe Acrobat Reader for Android fails completely.

Evince 3.10.3 complains about several syntax errors:

```
Syntax Error (60606): No current point in lineto
Syntax Error (60610): No current point in curveto
Syntax Error (60613): No current point in closepath
```

And http://www.pdf-tools.com/pdf/validate-pdfa-online.aspx tells that the pdf is invalid w.r.t all pdf standards.

**Comment by moepinet** [comment] 2015-09-03 07:18
I cannot reproduce that bug. Documentation opened so far on any PDF reader on Linux (zathura, evince), Preview (OSX, iOS), and Windows (Adobe Acrobat).

**Comment by diekmann** [comment] 2015-09-03 09:55
Steps to reproduce on ubuntu 14.04
1) Open evince from the shell. Do not detach.
2) Open documentation.pdf
3) Start scrolling
4) Watch evince cry in pain to stdout/stderr
http://i.imgur.com/o2s9eHv.png

**Comment by moepinet** [comment] 2016-04-06 19:36
should be fixed with latest version

**Closed as completed by moepinet** 2016-04-06 19:36 UTC
Labels: bug
